name: Run After Build Success

on:
  workflow_run:
    workflows: ["Build C++ File"]
    types:
      - completed

jobs:
  run-second:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "First workflow succeeded!"
