name: test

on:
  push:
    branches: [ "main" ]   # change if needed

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile hello.cpp
        run: g++ hello.cpp -o hello

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: hello-binary
          path: hello
  # second-job:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install compiler
  #       run: sudo apt-get update && sudo apt-get install -y g++

  #     - name: Compile
  #       run: g++ add.cpp -o main

  #     - name: Run
  #       run: ./main
  # third-job:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install compiler
  #       run: sudo apt-get update && sudo apt-get install -y g++

  #     - name: Compile
  #       run: g++ back.cpp -o main

  #     - name: Run
  #       run: ./main
